/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'id' : string,
  'status' : { 'present' : null } |
    { 'leave' : null } |
    { 'absent' : null },
  'date' : Time,
  'clockOutTime' : [] | [Time],
  'employeeId' : string,
  'clockInTime' : Time,
}
export interface Contact {
  'id' : string,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'company' : [] | [string],
  'address' : [] | [string],
  'phone' : [] | [string],
  'relationshipType' : string,
}
export interface CrmTask {
  'id' : string,
  'title' : string,
  'assignedTo' : Principal,
  'relatedOpportunity' : [] | [string],
  'createdAt' : Time,
  'completed' : boolean,
  'dueDate' : Time,
  'description' : [] | [string],
  'relatedContact' : [] | [string],
  'relatedLead' : [] | [string],
}
export type CurrencyCode = string;
export interface Department {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'managerId' : [] | [string],
}
export interface Employee {
  'id' : string,
  'status' : EmployeeStatus,
  'salary' : bigint,
  'userId' : [] | [Principal],
  'name' : string,
  'role' : string,
  'joiningDate' : Time,
  'departmentId' : string,
}
export type EmployeeStatus = { 'onLeave' : null } |
  { 'active' : null } |
  { 'terminated' : null } |
  { 'inactive' : null };
export type EventType = string;
export type ExternalBlob = Uint8Array;
export interface Lead {
  'id' : string,
  'source' : [] | [string],
  'ownerId' : Principal,
  'createdAt' : Time,
  'opportunityId' : [] | [string],
  'stage' : LeadStage,
  'notes' : Array<string>,
  'contactId' : string,
  'expectedRevenue' : [] | [bigint],
}
export type LeadStage = { 'new' : null } |
  { 'closed' : null } |
  { 'contacted' : null } |
  { 'qualified' : null };
export interface LeaveRequest {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'endDate' : Time,
  'createdAt' : Time,
  'employeeId' : string,
  'startDate' : Time,
  'reason' : string,
}
export interface Opportunity {
  'id' : string,
  'probability' : bigint,
  'value' : bigint,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : Time,
  'description' : [] | [string],
  'expectedCloseDate' : [] | [Time],
  'stage' : LeadStage,
  'notes' : Array<string>,
}
export interface Order {
  'id' : string,
  'status' : string,
  'total' : bigint,
  'paymentMethod' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'sku' : string,
  'productId' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Organization {
  'id' : OrganizationId,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'memberCount' : bigint,
  'description' : [] | [string],
  'updatedAt' : Time,
  'adminCount' : bigint,
}
export type OrganizationId = string;
export interface OrganizationMember {
  'organizationId' : string,
  'userId' : Principal,
  'joinedAt' : Time,
  'roles' : Array<OrganizationRole>,
}
export type OrganizationRole = { 'org_employee' : null } |
  { 'org_manager' : null } |
  { 'org_admin' : null };
export interface Payroll {
  'id' : string,
  'salary' : bigint,
  'createdAt' : Time,
  'deductions' : bigint,
  'netPay' : bigint,
  'employeeId' : string,
  'bonus' : bigint,
}
export interface PerformanceRecord {
  'id' : string,
  'kpis' : {
    'communication' : bigint,
    'teamwork' : bigint,
    'productivity' : bigint,
    'leadership' : bigint,
  },
  'createdAt' : Time,
  'reviewStatus' : PerformanceReviewStatus,
  'feedback' : [] | [string],
  'employeeId' : string,
}
export type PerformanceReviewStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface Product {
  'id' : string,
  'sku' : string,
  'categoryId' : string,
  'name' : string,
  'description' : string,
  'variants' : [] | [Array<string>],
  'stock' : bigint,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
  'digital' : boolean,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export type TransactionId = string;
export type TransactionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type TransactionType = { 'deposit' : null } |
  { 'withdrawal' : null } |
  { 'transfer' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'shippingAddress' : [] | [string],
  'paymentMethods' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wallet {
  'id' : WalletId,
  'organizationId' : OrganizationId,
  'balance' : bigint,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'description' : [] | [string],
  'isActive' : boolean,
  'updatedAt' : Time,
  'currency' : CurrencyCode,
}
export interface WalletEvent {
  'id' : WalletEventId,
  'organizationId' : OrganizationId,
  'createdAt' : Time,
  'createdBy' : Principal,
  'description' : string,
  'payload' : [] | [string],
  'walletId' : WalletId,
  'eventType' : EventType,
}
export type WalletEventId = string;
export type WalletId = string;
export interface WalletTransaction {
  'id' : TransactionId,
  'status' : TransactionStatus,
  'organizationId' : OrganizationId,
  'transactionType' : TransactionType,
  'createdAt' : Time,
  'createdBy' : Principal,
  'updatedAt' : Time,
  'currency' : CurrencyCode,
  'amount' : bigint,
  'walletId' : WalletId,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrganizationMember' : ActorMethod<
    [string, Principal, Array<OrganizationRole>],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrganization' : ActorMethod<[string, [] | [string]], Organization>,
  'getAttendance' : ActorMethod<[string], [] | [Attendance]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContact' : ActorMethod<[string], [] | [Contact]>,
  'getCrmTask' : ActorMethod<[string], [] | [CrmTask]>,
  'getDepartment' : ActorMethod<[string], [] | [Department]>,
  'getEmployee' : ActorMethod<[string], [] | [Employee]>,
  'getLead' : ActorMethod<[string], [] | [Lead]>,
  'getLeaveRequest' : ActorMethod<[string], [] | [LeaveRequest]>,
  'getOpportunity' : ActorMethod<[string], [] | [Opportunity]>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrganization' : ActorMethod<[string], [] | [Organization]>,
  'getOrganizationMembers' : ActorMethod<[string], Array<OrganizationMember>>,
  'getOrganizations' : ActorMethod<[], Array<Organization>>,
  'getPayroll' : ActorMethod<[string], [] | [Payroll]>,
  'getPerformanceRecord' : ActorMethod<[string], [] | [PerformanceRecord]>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWallet' : ActorMethod<[WalletId], [] | [Wallet]>,
  'getWalletEvent' : ActorMethod<[WalletEventId], [] | [WalletEvent]>,
  'getWalletTransaction' : ActorMethod<
    [TransactionId],
    [] | [WalletTransaction]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeOrganizationMember' : ActorMethod<[string, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrganizationMemberRoles' : ActorMethod<
    [string, Principal, Array<OrganizationRole>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];