/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const Attendance = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'present' : IDL.Null,
    'leave' : IDL.Null,
    'absent' : IDL.Null,
  }),
  'date' : Time,
  'clockOutTime' : IDL.Opt(Time),
  'employeeId' : IDL.Text,
  'clockInTime' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'shippingAddress' : IDL.Opt(IDL.Text),
  'paymentMethods' : IDL.Vec(IDL.Text),
});
export const Contact = IDL.Record({
  'id' : IDL.Text,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'relationshipType' : IDL.Text,
});
export const CrmTask = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'assignedTo' : IDL.Principal,
  'relatedOpportunity' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'completed' : IDL.Bool,
  'dueDate' : Time,
  'description' : IDL.Opt(IDL.Text),
  'relatedContact' : IDL.Opt(IDL.Text),
  'relatedLead' : IDL.Opt(IDL.Text),
});
export const Department = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'managerId' : IDL.Opt(IDL.Text),
});
export const EmployeeStatus = IDL.Variant({
  'onLeave' : IDL.Null,
  'active' : IDL.Null,
  'terminated' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'status' : EmployeeStatus,
  'salary' : IDL.Nat,
  'userId' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'role' : IDL.Text,
  'joiningDate' : Time,
  'departmentId' : IDL.Text,
});
export const LeadStage = IDL.Variant({
  'new' : IDL.Null,
  'closed' : IDL.Null,
  'contacted' : IDL.Null,
  'qualified' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'source' : IDL.Opt(IDL.Text),
  'ownerId' : IDL.Principal,
  'createdAt' : Time,
  'opportunityId' : IDL.Opt(IDL.Text),
  'stage' : LeadStage,
  'notes' : IDL.Vec(IDL.Text),
  'contactId' : IDL.Text,
  'expectedRevenue' : IDL.Opt(IDL.Nat),
});
export const LeaveRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'endDate' : Time,
  'createdAt' : Time,
  'employeeId' : IDL.Text,
  'startDate' : Time,
  'reason' : IDL.Text,
});
export const Opportunity = IDL.Record({
  'id' : IDL.Text,
  'probability' : IDL.Nat,
  'value' : IDL.Nat,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Opt(IDL.Text),
  'expectedCloseDate' : IDL.Opt(Time),
  'stage' : LeadStage,
  'notes' : IDL.Vec(IDL.Text),
});
export const OrderItem = IDL.Record({
  'sku' : IDL.Text,
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'total' : IDL.Nat,
  'paymentMethod' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'items' : IDL.Vec(OrderItem),
});
export const OrganizationId = IDL.Text;
export const Organization = IDL.Record({
  'id' : OrganizationId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'memberCount' : IDL.Nat,
  'description' : IDL.Opt(IDL.Text),
  'updatedAt' : Time,
  'adminCount' : IDL.Nat,
});
export const Payroll = IDL.Record({
  'id' : IDL.Text,
  'salary' : IDL.Nat,
  'createdAt' : Time,
  'deductions' : IDL.Nat,
  'netPay' : IDL.Nat,
  'employeeId' : IDL.Text,
  'bonus' : IDL.Nat,
});
export const PerformanceReviewStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const PerformanceRecord = IDL.Record({
  'id' : IDL.Text,
  'kpis' : IDL.Record({
    'communication' : IDL.Nat,
    'teamwork' : IDL.Nat,
    'productivity' : IDL.Nat,
    'leadership' : IDL.Nat,
  }),
  'createdAt' : Time,
  'reviewStatus' : PerformanceReviewStatus,
  'feedback' : IDL.Opt(IDL.Text),
  'employeeId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Text,
  'sku' : IDL.Text,
  'categoryId' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'variants' : IDL.Opt(IDL.Vec(IDL.Text)),
  'stock' : IDL.Nat,
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Nat,
  'digital' : IDL.Bool,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const WalletId = IDL.Text;
export const CurrencyCode = IDL.Text;
export const Wallet = IDL.Record({
  'id' : WalletId,
  'organizationId' : OrganizationId,
  'balance' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'description' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'updatedAt' : Time,
  'currency' : CurrencyCode,
});
export const WalletEventId = IDL.Text;
export const EventType = IDL.Text;
export const WalletEvent = IDL.Record({
  'id' : WalletEventId,
  'organizationId' : OrganizationId,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'payload' : IDL.Opt(IDL.Text),
  'walletId' : WalletId,
  'eventType' : EventType,
});
export const TransactionId = IDL.Text;
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
  'transfer' : IDL.Null,
});
export const WalletTransaction = IDL.Record({
  'id' : TransactionId,
  'status' : TransactionStatus,
  'organizationId' : OrganizationId,
  'transactionType' : TransactionType,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'updatedAt' : Time,
  'currency' : CurrencyCode,
  'amount' : IDL.Nat,
  'walletId' : WalletId,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAttendance' : IDL.Func([IDL.Text], [IDL.Opt(Attendance)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContact' : IDL.Func([IDL.Text], [IDL.Opt(Contact)], ['query']),
  'getCrmTask' : IDL.Func([IDL.Text], [IDL.Opt(CrmTask)], ['query']),
  'getDepartment' : IDL.Func([IDL.Text], [IDL.Opt(Department)], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
  'getLead' : IDL.Func([IDL.Text], [IDL.Opt(Lead)], ['query']),
  'getLeaveRequest' : IDL.Func([IDL.Text], [IDL.Opt(LeaveRequest)], ['query']),
  'getOpportunity' : IDL.Func([IDL.Text], [IDL.Opt(Opportunity)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrganization' : IDL.Func([IDL.Text], [IDL.Opt(Organization)], ['query']),
  'getPayroll' : IDL.Func([IDL.Text], [IDL.Opt(Payroll)], ['query']),
  'getPerformanceRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PerformanceRecord)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWallet' : IDL.Func([WalletId], [IDL.Opt(Wallet)], ['query']),
  'getWalletEvent' : IDL.Func(
      [WalletEventId],
      [IDL.Opt(WalletEvent)],
      ['query'],
    ),
  'getWalletTransaction' : IDL.Func(
      [TransactionId],
      [IDL.Opt(WalletTransaction)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const Attendance = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'present' : IDL.Null,
      'leave' : IDL.Null,
      'absent' : IDL.Null,
    }),
    'date' : Time,
    'clockOutTime' : IDL.Opt(Time),
    'employeeId' : IDL.Text,
    'clockInTime' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'shippingAddress' : IDL.Opt(IDL.Text),
    'paymentMethods' : IDL.Vec(IDL.Text),
  });
  const Contact = IDL.Record({
    'id' : IDL.Text,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'relationshipType' : IDL.Text,
  });
  const CrmTask = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'assignedTo' : IDL.Principal,
    'relatedOpportunity' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'completed' : IDL.Bool,
    'dueDate' : Time,
    'description' : IDL.Opt(IDL.Text),
    'relatedContact' : IDL.Opt(IDL.Text),
    'relatedLead' : IDL.Opt(IDL.Text),
  });
  const Department = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'managerId' : IDL.Opt(IDL.Text),
  });
  const EmployeeStatus = IDL.Variant({
    'onLeave' : IDL.Null,
    'active' : IDL.Null,
    'terminated' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'status' : EmployeeStatus,
    'salary' : IDL.Nat,
    'userId' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'role' : IDL.Text,
    'joiningDate' : Time,
    'departmentId' : IDL.Text,
  });
  const LeadStage = IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Null,
    'contacted' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'source' : IDL.Opt(IDL.Text),
    'ownerId' : IDL.Principal,
    'createdAt' : Time,
    'opportunityId' : IDL.Opt(IDL.Text),
    'stage' : LeadStage,
    'notes' : IDL.Vec(IDL.Text),
    'contactId' : IDL.Text,
    'expectedRevenue' : IDL.Opt(IDL.Nat),
  });
  const LeaveRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'endDate' : Time,
    'createdAt' : Time,
    'employeeId' : IDL.Text,
    'startDate' : Time,
    'reason' : IDL.Text,
  });
  const Opportunity = IDL.Record({
    'id' : IDL.Text,
    'probability' : IDL.Nat,
    'value' : IDL.Nat,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Opt(IDL.Text),
    'expectedCloseDate' : IDL.Opt(Time),
    'stage' : LeadStage,
    'notes' : IDL.Vec(IDL.Text),
  });
  const OrderItem = IDL.Record({
    'sku' : IDL.Text,
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'total' : IDL.Nat,
    'paymentMethod' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'items' : IDL.Vec(OrderItem),
  });
  const OrganizationId = IDL.Text;
  const Organization = IDL.Record({
    'id' : OrganizationId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'memberCount' : IDL.Nat,
    'description' : IDL.Opt(IDL.Text),
    'updatedAt' : Time,
    'adminCount' : IDL.Nat,
  });
  const Payroll = IDL.Record({
    'id' : IDL.Text,
    'salary' : IDL.Nat,
    'createdAt' : Time,
    'deductions' : IDL.Nat,
    'netPay' : IDL.Nat,
    'employeeId' : IDL.Text,
    'bonus' : IDL.Nat,
  });
  const PerformanceReviewStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const PerformanceRecord = IDL.Record({
    'id' : IDL.Text,
    'kpis' : IDL.Record({
      'communication' : IDL.Nat,
      'teamwork' : IDL.Nat,
      'productivity' : IDL.Nat,
      'leadership' : IDL.Nat,
    }),
    'createdAt' : Time,
    'reviewStatus' : PerformanceReviewStatus,
    'feedback' : IDL.Opt(IDL.Text),
    'employeeId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Text,
    'sku' : IDL.Text,
    'categoryId' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'variants' : IDL.Opt(IDL.Vec(IDL.Text)),
    'stock' : IDL.Nat,
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Nat,
    'digital' : IDL.Bool,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const WalletId = IDL.Text;
  const CurrencyCode = IDL.Text;
  const Wallet = IDL.Record({
    'id' : WalletId,
    'organizationId' : OrganizationId,
    'balance' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'description' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'updatedAt' : Time,
    'currency' : CurrencyCode,
  });
  const WalletEventId = IDL.Text;
  const EventType = IDL.Text;
  const WalletEvent = IDL.Record({
    'id' : WalletEventId,
    'organizationId' : OrganizationId,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'payload' : IDL.Opt(IDL.Text),
    'walletId' : WalletId,
    'eventType' : EventType,
  });
  const TransactionId = IDL.Text;
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
    'transfer' : IDL.Null,
  });
  const WalletTransaction = IDL.Record({
    'id' : TransactionId,
    'status' : TransactionStatus,
    'organizationId' : OrganizationId,
    'transactionType' : TransactionType,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'updatedAt' : Time,
    'currency' : CurrencyCode,
    'amount' : IDL.Nat,
    'walletId' : WalletId,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAttendance' : IDL.Func([IDL.Text], [IDL.Opt(Attendance)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContact' : IDL.Func([IDL.Text], [IDL.Opt(Contact)], ['query']),
    'getCrmTask' : IDL.Func([IDL.Text], [IDL.Opt(CrmTask)], ['query']),
    'getDepartment' : IDL.Func([IDL.Text], [IDL.Opt(Department)], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
    'getLead' : IDL.Func([IDL.Text], [IDL.Opt(Lead)], ['query']),
    'getLeaveRequest' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LeaveRequest)],
        ['query'],
      ),
    'getOpportunity' : IDL.Func([IDL.Text], [IDL.Opt(Opportunity)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrganization' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Organization)],
        ['query'],
      ),
    'getPayroll' : IDL.Func([IDL.Text], [IDL.Opt(Payroll)], ['query']),
    'getPerformanceRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PerformanceRecord)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWallet' : IDL.Func([WalletId], [IDL.Opt(Wallet)], ['query']),
    'getWalletEvent' : IDL.Func(
        [WalletEventId],
        [IDL.Opt(WalletEvent)],
        ['query'],
      ),
    'getWalletTransaction' : IDL.Func(
        [TransactionId],
        [IDL.Opt(WalletTransaction)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };