/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    shippingAddress?: string;
    paymentMethods: Array<string>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type WalletEventId = string;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Payroll {
    id: string;
    salary: bigint;
    createdAt: Time;
    deductions: bigint;
    netPay: bigint;
    employeeId: string;
    bonus: bigint;
}
export interface OrderItem {
    sku: string;
    productId: string;
    quantity: bigint;
    price: bigint;
}
export interface WalletTransaction {
    id: TransactionId;
    status: TransactionStatus;
    organizationId: OrganizationId;
    transactionType: TransactionType;
    createdAt: Time;
    createdBy: Principal;
    updatedAt: Time;
    currency: CurrencyCode;
    amount: bigint;
    walletId: WalletId;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface WalletSummaryData {
    events: Array<WalletEvent>;
    wallet: Wallet;
    transactions: Array<WalletTransaction>;
}
export interface WalletEvent {
    id: WalletEventId;
    organizationId: OrganizationId;
    createdAt: Time;
    createdBy: Principal;
    description: string;
    payload?: string;
    walletId: WalletId;
    eventType: EventType;
}
export interface Wallet {
    id: WalletId;
    organizationId: OrganizationId;
    balance: bigint;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    description?: string;
    isActive: boolean;
    updatedAt: Time;
    currency: CurrencyCode;
}
export type TransactionId = string;
export interface PerformanceRecord {
    id: string;
    kpis: {
        communication: bigint;
        teamwork: bigint;
        productivity: bigint;
        leadership: bigint;
    };
    createdAt: Time;
    reviewStatus: PerformanceReviewStatus;
    feedback?: string;
    employeeId: string;
}
export interface LeaveRequest {
    id: string;
    status: Variant_pending_approved_rejected;
    endDate: Time;
    createdAt: Time;
    employeeId: string;
    startDate: Time;
    reason: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Lead {
    id: string;
    source?: string;
    ownerId: Principal;
    createdAt: Time;
    opportunityId?: string;
    stage: LeadStage;
    notes: Array<string>;
    contactId: string;
    expectedRevenue?: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Employee {
    id: string;
    status: EmployeeStatus;
    salary: bigint;
    userId?: Principal;
    name: string;
    role: string;
    joiningDate: Time;
    departmentId: string;
}
export interface CrmTask {
    id: string;
    title: string;
    assignedTo: Principal;
    relatedOpportunity?: string;
    createdAt: Time;
    completed: boolean;
    dueDate: Time;
    description?: string;
    relatedContact?: string;
    relatedLead?: string;
}
export interface SidebarFinancialsResponse {
    financialSections: Array<SidebarFinancialSection>;
    wallets: Array<WalletOverviewResponse>;
    events: Array<WalletEvent>;
    transactions: Array<WalletTransaction>;
}
export interface Contact {
    id: string;
    ownerId: Principal;
    name: string;
    createdAt: Time;
    email: string;
    company?: string;
    address?: string;
    phone?: string;
    relationshipType: string;
}
export interface Attendance {
    id: string;
    status: Variant_present_leave_absent;
    date: Time;
    clockOutTime?: Time;
    employeeId: string;
    clockInTime: Time;
}
export interface WalletOverviewResponse {
    id: WalletId;
    balance: bigint;
    name: string;
    description?: string;
    isActive: boolean;
    currency: string;
    eventCount: bigint;
    transactionCount: bigint;
}
export interface OrganizationMember {
    organizationId: string;
    userId: Principal;
    joinedAt: Time;
    roles: Array<OrganizationRole>;
}
export interface Order {
    id: string;
    status: string;
    total: bigint;
    paymentMethod: string;
    userId: Principal;
    createdAt: Time;
    items: Array<OrderItem>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Opportunity {
    id: string;
    probability: bigint;
    value: bigint;
    ownerId: Principal;
    name: string;
    createdAt: Time;
    description?: string;
    expectedCloseDate?: Time;
    stage: LeadStage;
    notes: Array<string>;
}
export interface Department {
    id: string;
    name: string;
    createdAt: Time;
    managerId?: string;
}
export type EventType = string;
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type CurrencyCode = string;
export interface SidebarFinancialSection {
    overviewData: {
        transactionVolume: bigint;
        activeWallets: bigint;
        recentTransactions: Array<WalletTransaction>;
        totalBalance: bigint;
    };
    sectionName: string;
}
export type OrganizationId = string;
export type WalletId = string;
export interface Organization {
    id: OrganizationId;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    memberCount: bigint;
    description?: string;
    updatedAt: Time;
    adminCount: bigint;
}
export interface Product {
    id: string;
    sku: string;
    categoryId: string;
    name: string;
    description: string;
    variants?: Array<string>;
    stock: bigint;
    image?: ExternalBlob;
    price: bigint;
    digital: boolean;
}
export enum EmployeeStatus {
    onLeave = "onLeave",
    active = "active",
    terminated = "terminated",
    inactive = "inactive"
}
export enum LeadStage {
    new_ = "new",
    closed = "closed",
    contacted = "contacted",
    qualified = "qualified"
}
export enum OrganizationRole {
    org_employee = "org_employee",
    org_manager = "org_manager",
    org_admin = "org_admin"
}
export enum PerformanceReviewStatus {
    notStarted = "notStarted",
    completed = "completed",
    inProgress = "inProgress"
}
export enum TransactionStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum TransactionType {
    deposit = "deposit",
    withdrawal = "withdrawal",
    transfer = "transfer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Variant_present_leave_absent {
    present = "present",
    leave = "leave",
    absent = "absent"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrganizationMember(orgId: string, user: Principal, roles: Array<OrganizationRole>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createOrganization(name: string, description: string | null): Promise<Organization>;
    getAttendance(_attendanceId: string): Promise<Attendance | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContact(_contactId: string): Promise<Contact | null>;
    getCrmTask(_taskId: string): Promise<CrmTask | null>;
    getDepartment(_departmentId: string): Promise<Department | null>;
    getEmployee(_employeeId: string): Promise<Employee | null>;
    getLead(_leadId: string): Promise<Lead | null>;
    getLeaveRequest(_leaveId: string): Promise<LeaveRequest | null>;
    getOpportunity(_opportunityId: string): Promise<Opportunity | null>;
    getOrder(_orderId: string): Promise<Order | null>;
    getOrganization(_orgId: string): Promise<Organization | null>;
    getOrganizationMembers(orgId: string): Promise<Array<OrganizationMember>>;
    getOrganizationSidebarFinancials(orgId: string): Promise<SidebarFinancialsResponse>;
    getOrganizationWalletEvents(orgId: string, walletId: WalletId): Promise<Array<WalletEvent>>;
    getOrganizationWalletTransactions(orgId: string, walletId: WalletId): Promise<Array<WalletTransaction>>;
    getOrganizationWallets(orgId: string): Promise<Array<Wallet>>;
    getOrganizationWalletsSummary(orgId: string): Promise<Array<WalletOverviewResponse>>;
    getOrganizations(): Promise<Array<Organization>>;
    getPayroll(_payrollId: string): Promise<Payroll | null>;
    getPerformanceRecord(_recordId: string): Promise<PerformanceRecord | null>;
    getProduct(_productId: string): Promise<Product | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWallet(_walletId: WalletId): Promise<Wallet | null>;
    getWalletEvent(_eventId: WalletEventId): Promise<WalletEvent | null>;
    getWalletSummary(walletId: WalletId): Promise<WalletSummaryData>;
    getWalletTransaction(_transactionId: TransactionId): Promise<WalletTransaction | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    removeOrganizationMember(orgId: string, user: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateOrganizationMemberRoles(orgId: string, user: Principal, roles: Array<OrganizationRole>): Promise<void>;
}
import type { Attendance as _Attendance, Contact as _Contact, CrmTask as _CrmTask, CurrencyCode as _CurrencyCode, Department as _Department, Employee as _Employee, EmployeeStatus as _EmployeeStatus, EventType as _EventType, ExternalBlob as _ExternalBlob, Lead as _Lead, LeadStage as _LeadStage, LeaveRequest as _LeaveRequest, Opportunity as _Opportunity, Order as _Order, Organization as _Organization, OrganizationId as _OrganizationId, OrganizationMember as _OrganizationMember, OrganizationRole as _OrganizationRole, Payroll as _Payroll, PerformanceRecord as _PerformanceRecord, PerformanceReviewStatus as _PerformanceReviewStatus, Product as _Product, SidebarFinancialSection as _SidebarFinancialSection, SidebarFinancialsResponse as _SidebarFinancialsResponse, StripeSessionStatus as _StripeSessionStatus, Time as _Time, TransactionId as _TransactionId, TransactionStatus as _TransactionStatus, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole, Wallet as _Wallet, WalletEvent as _WalletEvent, WalletEventId as _WalletEventId, WalletId as _WalletId, WalletOverviewResponse as _WalletOverviewResponse, WalletSummaryData as _WalletSummaryData, WalletTransaction as _WalletTransaction, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrganizationMember(arg0: string, arg1: Principal, arg2: Array<OrganizationRole>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrganizationMember(arg0, arg1, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrganizationMember(arg0, arg1, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrganization(arg0: string, arg1: string | null): Promise<Organization> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrganization(arg0, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Organization_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrganization(arg0, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Organization_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendance(arg0: string): Promise<Attendance | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendance(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendance(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContact(arg0: string): Promise<Contact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContact(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContact(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCrmTask(arg0: string): Promise<CrmTask | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrmTask(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrmTask(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDepartment(arg0: string): Promise<Department | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartment(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartment(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployee(arg0: string): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLead(arg0: string): Promise<Lead | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaveRequest(arg0: string): Promise<LeaveRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveRequest(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveRequest(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpportunity(arg0: string): Promise<Opportunity | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpportunity(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpportunity(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganization(arg0: string): Promise<Organization | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganization(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganization(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganizationMembers(arg0: string): Promise<Array<OrganizationMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganizationMembers(arg0);
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganizationMembers(arg0);
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganizationSidebarFinancials(arg0: string): Promise<SidebarFinancialsResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganizationSidebarFinancials(arg0);
                return from_candid_SidebarFinancialsResponse_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganizationSidebarFinancials(arg0);
            return from_candid_SidebarFinancialsResponse_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganizationWalletEvents(arg0: string, arg1: WalletId): Promise<Array<WalletEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganizationWalletEvents(arg0, arg1);
                return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganizationWalletEvents(arg0, arg1);
            return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganizationWalletTransactions(arg0: string, arg1: WalletId): Promise<Array<WalletTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganizationWalletTransactions(arg0, arg1);
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganizationWalletTransactions(arg0, arg1);
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganizationWallets(arg0: string): Promise<Array<Wallet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganizationWallets(arg0);
                return from_candid_vec_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganizationWallets(arg0);
            return from_candid_vec_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganizationWalletsSummary(arg0: string): Promise<Array<WalletOverviewResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganizationWalletsSummary(arg0);
                return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganizationWalletsSummary(arg0);
            return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganizations(): Promise<Array<Organization>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganizations();
                return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganizations();
            return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayroll(arg0: string): Promise<Payroll | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayroll(arg0);
                return from_candid_opt_n85(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayroll(arg0);
            return from_candid_opt_n85(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerformanceRecord(arg0: string): Promise<PerformanceRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformanceRecord(arg0);
                return from_candid_opt_n86(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformanceRecord(arg0);
            return from_candid_opt_n86(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n91(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n91(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n97(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n97(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWallet(arg0: WalletId): Promise<Wallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallet(arg0);
                return from_candid_opt_n100(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallet(arg0);
            return from_candid_opt_n100(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletEvent(arg0: WalletEventId): Promise<WalletEvent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletEvent(arg0);
                return from_candid_opt_n101(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletEvent(arg0);
            return from_candid_opt_n101(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletSummary(arg0: WalletId): Promise<WalletSummaryData> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletSummary(arg0);
                return from_candid_WalletSummaryData_n102(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletSummary(arg0);
            return from_candid_WalletSummaryData_n102(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletTransaction(arg0: TransactionId): Promise<WalletTransaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletTransaction(arg0);
                return from_candid_opt_n104(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletTransaction(arg0);
            return from_candid_opt_n104(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async removeOrganizationMember(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeOrganizationMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeOrganizationMember(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n105(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n105(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateOrganizationMemberRoles(arg0: string, arg1: Principal, arg2: Array<OrganizationRole>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrganizationMemberRoles(arg0, arg1, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrganizationMemberRoles(arg0, arg1, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_Attendance_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attendance): Attendance {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Contact_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contact): Contact {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_CrmTask_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CrmTask): CrmTask {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Department_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Department): Department {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_EmployeeStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeStatus): EmployeeStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Employee_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LeadStage_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStage): LeadStage {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveRequest_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveRequest): LeaveRequest {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Opportunity_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Opportunity): Opportunity {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_OrganizationMember_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrganizationMember): OrganizationMember {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_OrganizationRole_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrganizationRole): OrganizationRole {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Organization_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Organization): Organization {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PerformanceRecord_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PerformanceRecord): PerformanceRecord {
    return from_candid_record_n88(_uploadFile, _downloadFile, value);
}
function from_candid_PerformanceReviewStatus_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PerformanceReviewStatus): PerformanceReviewStatus {
    return from_candid_variant_n90(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n93(_uploadFile, _downloadFile, value);
}
function from_candid_SidebarFinancialSection_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SidebarFinancialSection): SidebarFinancialSection {
    return from_candid_record_n66(_uploadFile, _downloadFile, value);
}
function from_candid_SidebarFinancialsResponse_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SidebarFinancialsResponse): SidebarFinancialsResponse {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n98(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_WalletEvent_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletEvent): WalletEvent {
    return from_candid_record_n80(_uploadFile, _downloadFile, value);
}
function from_candid_WalletOverviewResponse_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletOverviewResponse): WalletOverviewResponse {
    return from_candid_record_n77(_uploadFile, _downloadFile, value);
}
function from_candid_WalletSummaryData_n102(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletSummaryData): WalletSummaryData {
    return from_candid_record_n103(_uploadFile, _downloadFile, value);
}
function from_candid_WalletTransaction_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletTransaction): WalletTransaction {
    return from_candid_record_n70(_uploadFile, _downloadFile, value);
}
function from_candid_Wallet_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Wallet): Wallet {
    return from_candid_record_n83(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Wallet]): Wallet | null {
    return value.length === 0 ? null : from_candid_Wallet_n82(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n101(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WalletEvent]): WalletEvent | null {
    return value.length === 0 ? null : from_candid_WalletEvent_n79(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n104(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WalletTransaction]): WalletTransaction | null {
    return value.length === 0 ? null : from_candid_WalletTransaction_n69(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Attendance]): Attendance | null {
    return value.length === 0 ? null : from_candid_Attendance_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contact]): Contact | null {
    return value.length === 0 ? null : from_candid_Contact_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CrmTask]): CrmTask | null {
    return value.length === 0 ? null : from_candid_CrmTask_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Department]): Department | null {
    return value.length === 0 ? null : from_candid_Department_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Employee | null {
    return value.length === 0 ? null : from_candid_Employee_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lead]): Lead | null {
    return value.length === 0 ? null : from_candid_Lead_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LeaveRequest]): LeaveRequest | null {
    return value.length === 0 ? null : from_candid_LeaveRequest_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Opportunity]): Opportunity | null {
    return value.length === 0 ? null : from_candid_Opportunity_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Organization]): Organization | null {
    return value.length === 0 ? null : from_candid_Organization_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payroll]): Payroll | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PerformanceRecord]): PerformanceRecord | null {
    return value.length === 0 ? null : from_candid_PerformanceRecord_n87(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Promise<Product | null> {
    return value.length === 0 ? null : await from_candid_Product_n92(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n96(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n103(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    events: Array<_WalletEvent>;
    wallet: _Wallet;
    transactions: Array<_WalletTransaction>;
}): {
    events: Array<WalletEvent>;
    wallet: Wallet;
    transactions: Array<WalletTransaction>;
} {
    return {
        events: from_candid_vec_n78(_uploadFile, _downloadFile, value.events),
        wallet: from_candid_Wallet_n82(_uploadFile, _downloadFile, value.wallet),
        transactions: from_candid_vec_n68(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrganizationId;
    name: string;
    createdAt: _Time;
    createdBy: Principal;
    memberCount: bigint;
    description: [] | [string];
    updatedAt: _Time;
    adminCount: bigint;
}): {
    id: OrganizationId;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    memberCount: bigint;
    description?: string;
    updatedAt: Time;
    adminCount: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        memberCount: value.memberCount,
        description: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.description)),
        updatedAt: value.updatedAt,
        adminCount: value.adminCount
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        present: null;
    } | {
        leave: null;
    } | {
        absent: null;
    };
    date: _Time;
    clockOutTime: [] | [_Time];
    employeeId: string;
    clockInTime: _Time;
}): {
    id: string;
    status: Variant_present_leave_absent;
    date: Time;
    clockOutTime?: Time;
    employeeId: string;
    clockInTime: Time;
} {
    return {
        id: value.id,
        status: from_candid_variant_n20(_uploadFile, _downloadFile, value.status),
        date: value.date,
        clockOutTime: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.clockOutTime)),
        employeeId: value.employeeId,
        clockInTime: value.clockInTime
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    shippingAddress: [] | [string];
    paymentMethods: Array<string>;
}): {
    name: string;
    shippingAddress?: string;
    paymentMethods: Array<string>;
} {
    return {
        name: value.name,
        shippingAddress: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.shippingAddress)),
        paymentMethods: value.paymentMethods
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    ownerId: Principal;
    name: string;
    createdAt: _Time;
    email: string;
    company: [] | [string];
    address: [] | [string];
    phone: [] | [string];
    relationshipType: string;
}): {
    id: string;
    ownerId: Principal;
    name: string;
    createdAt: Time;
    email: string;
    company?: string;
    address?: string;
    phone?: string;
    relationshipType: string;
} {
    return {
        id: value.id,
        ownerId: value.ownerId,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        company: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.company)),
        address: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.address)),
        phone: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.phone)),
        relationshipType: value.relationshipType
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    assignedTo: Principal;
    relatedOpportunity: [] | [string];
    createdAt: _Time;
    completed: boolean;
    dueDate: _Time;
    description: [] | [string];
    relatedContact: [] | [string];
    relatedLead: [] | [string];
}): {
    id: string;
    title: string;
    assignedTo: Principal;
    relatedOpportunity?: string;
    createdAt: Time;
    completed: boolean;
    dueDate: Time;
    description?: string;
    relatedContact?: string;
    relatedLead?: string;
} {
    return {
        id: value.id,
        title: value.title,
        assignedTo: value.assignedTo,
        relatedOpportunity: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.relatedOpportunity)),
        createdAt: value.createdAt,
        completed: value.completed,
        dueDate: value.dueDate,
        description: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.description)),
        relatedContact: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.relatedContact)),
        relatedLead: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.relatedLead))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: _Time;
    managerId: [] | [string];
}): {
    id: string;
    name: string;
    createdAt: Time;
    managerId?: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        managerId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.managerId))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _EmployeeStatus;
    salary: bigint;
    userId: [] | [Principal];
    name: string;
    role: string;
    joiningDate: _Time;
    departmentId: string;
}): {
    id: string;
    status: EmployeeStatus;
    salary: bigint;
    userId?: Principal;
    name: string;
    role: string;
    joiningDate: Time;
    departmentId: string;
} {
    return {
        id: value.id,
        status: from_candid_EmployeeStatus_n39(_uploadFile, _downloadFile, value.status),
        salary: value.salary,
        userId: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.userId)),
        name: value.name,
        role: value.role,
        joiningDate: value.joiningDate,
        departmentId: value.departmentId
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    source: [] | [string];
    ownerId: Principal;
    createdAt: _Time;
    opportunityId: [] | [string];
    stage: _LeadStage;
    notes: Array<string>;
    contactId: string;
    expectedRevenue: [] | [bigint];
}): {
    id: string;
    source?: string;
    ownerId: Principal;
    createdAt: Time;
    opportunityId?: string;
    stage: LeadStage;
    notes: Array<string>;
    contactId: string;
    expectedRevenue?: bigint;
} {
    return {
        id: value.id,
        source: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.source)),
        ownerId: value.ownerId,
        createdAt: value.createdAt,
        opportunityId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.opportunityId)),
        stage: from_candid_LeadStage_n45(_uploadFile, _downloadFile, value.stage),
        notes: value.notes,
        contactId: value.contactId,
        expectedRevenue: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.expectedRevenue))
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    endDate: _Time;
    createdAt: _Time;
    employeeId: string;
    startDate: _Time;
    reason: string;
}): {
    id: string;
    status: Variant_pending_approved_rejected;
    endDate: Time;
    createdAt: Time;
    employeeId: string;
    startDate: Time;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n50(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        createdAt: value.createdAt,
        employeeId: value.employeeId,
        startDate: value.startDate,
        reason: value.reason
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    probability: bigint;
    value: bigint;
    ownerId: Principal;
    name: string;
    createdAt: _Time;
    description: [] | [string];
    expectedCloseDate: [] | [_Time];
    stage: _LeadStage;
    notes: Array<string>;
}): {
    id: string;
    probability: bigint;
    value: bigint;
    ownerId: Principal;
    name: string;
    createdAt: Time;
    description?: string;
    expectedCloseDate?: Time;
    stage: LeadStage;
    notes: Array<string>;
} {
    return {
        id: value.id,
        probability: value.probability,
        value: value.value,
        ownerId: value.ownerId,
        name: value.name,
        createdAt: value.createdAt,
        description: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.description)),
        expectedCloseDate: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.expectedCloseDate)),
        stage: from_candid_LeadStage_n45(_uploadFile, _downloadFile, value.stage),
        notes: value.notes
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizationId: string;
    userId: Principal;
    joinedAt: _Time;
    roles: Array<_OrganizationRole>;
}): {
    organizationId: string;
    userId: Principal;
    joinedAt: Time;
    roles: Array<OrganizationRole>;
} {
    return {
        organizationId: value.organizationId,
        userId: value.userId,
        joinedAt: value.joinedAt,
        roles: from_candid_vec_n59(_uploadFile, _downloadFile, value.roles)
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    financialSections: Array<_SidebarFinancialSection>;
    wallets: Array<_WalletOverviewResponse>;
    events: Array<_WalletEvent>;
    transactions: Array<_WalletTransaction>;
}): {
    financialSections: Array<SidebarFinancialSection>;
    wallets: Array<WalletOverviewResponse>;
    events: Array<WalletEvent>;
    transactions: Array<WalletTransaction>;
} {
    return {
        financialSections: from_candid_vec_n64(_uploadFile, _downloadFile, value.financialSections),
        wallets: from_candid_vec_n75(_uploadFile, _downloadFile, value.wallets),
        events: from_candid_vec_n78(_uploadFile, _downloadFile, value.events),
        transactions: from_candid_vec_n68(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    overviewData: {
        transactionVolume: bigint;
        activeWallets: bigint;
        recentTransactions: Array<_WalletTransaction>;
        totalBalance: bigint;
    };
    sectionName: string;
}): {
    overviewData: {
        transactionVolume: bigint;
        activeWallets: bigint;
        recentTransactions: Array<WalletTransaction>;
        totalBalance: bigint;
    };
    sectionName: string;
} {
    return {
        overviewData: from_candid_record_n67(_uploadFile, _downloadFile, value.overviewData),
        sectionName: value.sectionName
    };
}
function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionVolume: bigint;
    activeWallets: bigint;
    recentTransactions: Array<_WalletTransaction>;
    totalBalance: bigint;
}): {
    transactionVolume: bigint;
    activeWallets: bigint;
    recentTransactions: Array<WalletTransaction>;
    totalBalance: bigint;
} {
    return {
        transactionVolume: value.transactionVolume,
        activeWallets: value.activeWallets,
        recentTransactions: from_candid_vec_n68(_uploadFile, _downloadFile, value.recentTransactions),
        totalBalance: value.totalBalance
    };
}
function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransactionId;
    status: _TransactionStatus;
    organizationId: _OrganizationId;
    transactionType: _TransactionType;
    createdAt: _Time;
    createdBy: Principal;
    updatedAt: _Time;
    currency: _CurrencyCode;
    amount: bigint;
    walletId: _WalletId;
}): {
    id: TransactionId;
    status: TransactionStatus;
    organizationId: OrganizationId;
    transactionType: TransactionType;
    createdAt: Time;
    createdBy: Principal;
    updatedAt: Time;
    currency: CurrencyCode;
    amount: bigint;
    walletId: WalletId;
} {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n71(_uploadFile, _downloadFile, value.status),
        organizationId: value.organizationId,
        transactionType: from_candid_TransactionType_n73(_uploadFile, _downloadFile, value.transactionType),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        updatedAt: value.updatedAt,
        currency: value.currency,
        amount: value.amount,
        walletId: value.walletId
    };
}
function from_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WalletId;
    balance: bigint;
    name: string;
    description: [] | [string];
    isActive: boolean;
    currency: string;
    eventCount: bigint;
    transactionCount: bigint;
}): {
    id: WalletId;
    balance: bigint;
    name: string;
    description?: string;
    isActive: boolean;
    currency: string;
    eventCount: bigint;
    transactionCount: bigint;
} {
    return {
        id: value.id,
        balance: value.balance,
        name: value.name,
        description: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.description)),
        isActive: value.isActive,
        currency: value.currency,
        eventCount: value.eventCount,
        transactionCount: value.transactionCount
    };
}
function from_candid_record_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WalletEventId;
    organizationId: _OrganizationId;
    createdAt: _Time;
    createdBy: Principal;
    description: string;
    payload: [] | [string];
    walletId: _WalletId;
    eventType: _EventType;
}): {
    id: WalletEventId;
    organizationId: OrganizationId;
    createdAt: Time;
    createdBy: Principal;
    description: string;
    payload?: string;
    walletId: WalletId;
    eventType: EventType;
} {
    return {
        id: value.id,
        organizationId: value.organizationId,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        payload: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.payload)),
        walletId: value.walletId,
        eventType: value.eventType
    };
}
function from_candid_record_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WalletId;
    organizationId: _OrganizationId;
    balance: bigint;
    name: string;
    createdAt: _Time;
    createdBy: Principal;
    description: [] | [string];
    isActive: boolean;
    updatedAt: _Time;
    currency: _CurrencyCode;
}): {
    id: WalletId;
    organizationId: OrganizationId;
    balance: bigint;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    description?: string;
    isActive: boolean;
    updatedAt: Time;
    currency: CurrencyCode;
} {
    return {
        id: value.id,
        organizationId: value.organizationId,
        balance: value.balance,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.description)),
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        currency: value.currency
    };
}
function from_candid_record_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    kpis: {
        communication: bigint;
        teamwork: bigint;
        productivity: bigint;
        leadership: bigint;
    };
    createdAt: _Time;
    reviewStatus: _PerformanceReviewStatus;
    feedback: [] | [string];
    employeeId: string;
}): {
    id: string;
    kpis: {
        communication: bigint;
        teamwork: bigint;
        productivity: bigint;
        leadership: bigint;
    };
    createdAt: Time;
    reviewStatus: PerformanceReviewStatus;
    feedback?: string;
    employeeId: string;
} {
    return {
        id: value.id,
        kpis: value.kpis,
        createdAt: value.createdAt,
        reviewStatus: from_candid_PerformanceReviewStatus_n89(_uploadFile, _downloadFile, value.reviewStatus),
        feedback: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.feedback)),
        employeeId: value.employeeId
    };
}
async function from_candid_record_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    sku: string;
    categoryId: string;
    name: string;
    description: string;
    variants: [] | [Array<string>];
    stock: bigint;
    image: [] | [_ExternalBlob];
    price: bigint;
    digital: boolean;
}): Promise<{
    id: string;
    sku: string;
    categoryId: string;
    name: string;
    description: string;
    variants?: Array<string>;
    stock: bigint;
    image?: ExternalBlob;
    price: bigint;
    digital: boolean;
}> {
    return {
        id: value.id,
        sku: value.sku,
        categoryId: value.categoryId,
        name: value.name,
        description: value.description,
        variants: record_opt_to_undefined(from_candid_opt_n94(_uploadFile, _downloadFile, value.variants)),
        stock: value.stock,
        image: record_opt_to_undefined(await from_candid_opt_n95(_uploadFile, _downloadFile, value.image)),
        price: value.price,
        digital: value.digital
    };
}
function from_candid_record_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    leave: null;
} | {
    absent: null;
}): Variant_present_leave_absent {
    return "present" in value ? Variant_present_leave_absent.present : "leave" in value ? Variant_present_leave_absent.leave : "absent" in value ? Variant_present_leave_absent.absent : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onLeave: null;
} | {
    active: null;
} | {
    terminated: null;
} | {
    inactive: null;
}): EmployeeStatus {
    return "onLeave" in value ? EmployeeStatus.onLeave : "active" in value ? EmployeeStatus.active : "terminated" in value ? EmployeeStatus.terminated : "inactive" in value ? EmployeeStatus.inactive : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    closed: null;
} | {
    contacted: null;
} | {
    qualified: null;
}): LeadStage {
    return "new" in value ? LeadStage.new : "closed" in value ? LeadStage.closed : "contacted" in value ? LeadStage.contacted : "qualified" in value ? LeadStage.qualified : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    org_employee: null;
} | {
    org_manager: null;
} | {
    org_admin: null;
}): OrganizationRole {
    return "org_employee" in value ? OrganizationRole.org_employee : "org_manager" in value ? OrganizationRole.org_manager : "org_admin" in value ? OrganizationRole.org_admin : value;
}
function from_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "completed" in value ? TransactionStatus.completed : "failed" in value ? TransactionStatus.failed : value;
}
function from_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deposit: null;
} | {
    withdrawal: null;
} | {
    transfer: null;
}): TransactionType {
    return "deposit" in value ? TransactionType.deposit : "withdrawal" in value ? TransactionType.withdrawal : "transfer" in value ? TransactionType.transfer : value;
}
function from_candid_variant_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): PerformanceReviewStatus {
    return "notStarted" in value ? PerformanceReviewStatus.notStarted : "completed" in value ? PerformanceReviewStatus.completed : "inProgress" in value ? PerformanceReviewStatus.inProgress : value;
}
function from_candid_variant_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n99(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrganizationMember>): Array<OrganizationMember> {
    return value.map((x)=>from_candid_OrganizationMember_n57(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrganizationRole>): Array<OrganizationRole> {
    return value.map((x)=>from_candid_OrganizationRole_n60(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SidebarFinancialSection>): Array<SidebarFinancialSection> {
    return value.map((x)=>from_candid_SidebarFinancialSection_n65(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WalletTransaction>): Array<WalletTransaction> {
    return value.map((x)=>from_candid_WalletTransaction_n69(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WalletOverviewResponse>): Array<WalletOverviewResponse> {
    return value.map((x)=>from_candid_WalletOverviewResponse_n76(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WalletEvent>): Array<WalletEvent> {
    return value.map((x)=>from_candid_WalletEvent_n79(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Wallet>): Array<Wallet> {
    return value.map((x)=>from_candid_Wallet_n82(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Organization>): Array<Organization> {
    return value.map((x)=>from_candid_Organization_n14(_uploadFile, _downloadFile, x));
}
function to_candid_OrganizationRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrganizationRole): _OrganizationRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n105(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n106(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n106(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    shippingAddress?: string;
    paymentMethods: Array<string>;
}): {
    name: string;
    shippingAddress: [] | [string];
    paymentMethods: Array<string>;
} {
    return {
        name: value.name,
        shippingAddress: value.shippingAddress ? candid_some(value.shippingAddress) : candid_none(),
        paymentMethods: value.paymentMethods
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrganizationRole): {
    org_employee: null;
} | {
    org_manager: null;
} | {
    org_admin: null;
} {
    return value == OrganizationRole.org_employee ? {
        org_employee: null
    } : value == OrganizationRole.org_manager ? {
        org_manager: null
    } : value == OrganizationRole.org_admin ? {
        org_admin: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OrganizationRole>): Array<_OrganizationRole> {
    return value.map((x)=>to_candid_OrganizationRole_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
